theme: jekyll-theme-cayman
title: Histoire du Jour de l'An 101
description: Cours d'introduction sur les grandes lignes et l'histoire du Jour de l'An
plugins:
- jekyll-menus
# Liste des catégories
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html
    # exemple -> /category/informatique/index.html

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
      # layout utilisé -> _layouts/category.html
